import { Dessert } from "lucide-react";

export const foodItems = [
  // Starters 

    {
      // id: 1,
      name: "Margherita Pizza",
      category: "Starters",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-1.png" ,
      description: "Classic margherita pizza with fresh basil and mozzarella.",
      price: "$ 15.99", 
    },
    {
      // id: 2,
      name: "Caesar Salad",
      category: "Starters",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-2.png",
      description: "Crisp romaine lettuce with Caesar dressing and croutons.",
      price: "$ 8.99",
    },
    {
      // id: 3,
      name: "Crispy Chicken Wings",
      category: "Starters",
      image: "https://png.pngtree.com/png-clipart/20241114/original/pngtree-chicken-wings-on-white-plate-png-image_17014036.png",
      description: "Juicy wings tossed in spicy BBQ sauce.",
      price: "$ 12.99",

    },
    {
      // id: 4,
      name: "Stuffed Mushrooms",
      category: "Starters",
      image: "https://thumbs.dreamstime.com/b/plate-baked-stuffed-mushrooms-isolated-white-background-highlighting-flavorful-appetizer-344168539.jpg",
      description: "Mushrooms filled with cheese, garlic, and herbs.",
      price: "$ 10.99",
    },
    {
      // id: 5,
      name: "Spring Rolls",
      category: "Starters",
      image: "https://png.pngtree.com/png-clipart/20241114/original/pngtree-crispy-spring-rolls-with-parsley-garnish-on-white-plate-png-image_17043113.png",
      description: "Crispy rolls packed with fresh veggies and soy sauce.",
      price: "$ 9.99",
    },
    {
      // id: 6,
      name: "Bruschetta",
      category: "Starters",
      image: "https://png.pngtree.com/png-vector/20230918/ourmid/pngtree-bruschetta-italian-food-png-image_10093556.png",
      description: "Toasted bread topped with tomatoes, basil, and olive oil.",
      price: "$ 7.99",


    },
    { 
      // id: 7,
      name: "Cheese Garlic Bread",
      category: "Starters",
      image: "https://img.freepik.com/premium-photo/round-wooden-plate-with-garlic-bread-cutout-transparent-background_1077802-444959.jpg",
      description: "Crunchy bread with melted cheese and garlic butter.",
      price: "$ 8.99",
    },
    {
      // id: 8,
      name: "Margherita Pizza",
      category: "Starters",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-3.png" ,
      description: "Classic margherita pizza with fresh basil and mozzarella.",
      price: "$ 15.99", 
      
    },


    // Dessert  
    {
      // id: 4,
      name: "Latte",
      category: "Main Course",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-2.png",
      description: "Creamy latte with a perfect balance of coffee and milk.",
      price: "$ 4.99",
    },
    {
      // id: 5,
      name: "Bruschetta",
      category: "Main Course",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-3.png",
      description: "Toasted bread topped with fresh tomatoes and basil.",
      price: "$ 7.99",
    },
    {
      // id: 6,
      name: "Grilled Chicken",
      category: "Main Course",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-1.png",
      description: "Juicy grilled chicken served with seasonal vegetables.",
      price: "$ 14.99",
    },
    {
      // id: 9,
      image: "https://www.shutterstock.com/image-photo/lava-cake-chocolate-coming-out-600nw-2500970875.jpg",
      name: "Chocolate Lava Cake",
      category: "Desserts",
      description: "Warm chocolate cake with a gooey molten center.",
      price: "$ 8.99",
    },
    {
      // id: 10,
      image: "https://img.freepik.com/premium-photo/tiramisu-white-plate-white-background-directly-view_864588-11646.jpg",
      name: "Tiramisu",
      category: "Desserts",
      description: "Classic Italian dessert with coffee-soaked layers and mascarpone.",
      price: "$ 7.99",
    },
    {
      // id: 11,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBGByQ80MvikGRjmcTeVhFvhZHWXvI7TRwsw&s",
      name: "Gulab Jamun",
      category: "Desserts",
      description: "Soft fried dumplings soaked in sugar syrup.",
      price: "$ 6.99",
    },
    {
      // id: 12,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuHEUCb-goB_UkThp8utWbzOzH3jWkj0PASA&s",
      name: "Cheesecake",
      category: "Desserts",
      description: "Creamy baked cheesecake with a biscuit base.",
      price: "$ 8.99",
    },
    {
      // id: 13,
      image: "https://www.shutterstock.com/image-photo/tasty-brownies-ice-cream-mint-600nw-2375561853.jpg",
      name: "Brownie with Ice Cream",
      category: "Desserts",
      description: "Rich chocolate brownie served with vanilla ice cream.",
      price: "$ 9.99",
    },

    // Main Course 
    {
      // id: 7,
      name: "Margherita Pizza",
      category: "Main Course",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-2.png" ,
      description: "Classic margherita pizza with fresh basil and mozzarella.",
      price: "$ 15.99", 
      
    },
    {
      // id: 8,
      name: "Fruit Salad",
      category: "Main Course",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-3.png",
      description: "Fresh mix of seasonal fruits.",
      price: "$ 5.99",
    },
    {
      // id: 9,
      name: "Chicken Wings",
      category: "Main Course",
      image: "https://png.pngtree.com/png-clipart/20241204/original/pngtree-a-plate-of-crispy-chicken-wings-coated-in-tangy-buffalo-sauce-png-image_17556762.png",
      description: "Crispy fried chicken served with your choice of sauce.",
      price: "$ 8.99",
    },
    {
      // id: 10,
      image: "https://media.istockphoto.com/id/898087604/photo/fish-dish-salmon-steak-and-vegetables.jpg?s=612x612&w=0&k=20&c=jTXkvfw6naChqYqY3JnQoHZyRdd0y-C6uVwVns-V3UU=",
      name: "Grilled Salmon",
      category: "Main Course",
      description: "Freshly grilled salmon served with lemon butter sauce.",
      price: "$ 19.99",
    },
    {
      // id: 11,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm-mXNgX_BHASEeEEnSeVWKWptsRHLefXJgA&s",
      name: "Paneer Butter Masala",
      category: "Main Course",
      description: "Soft paneer cubes in a rich tomato and butter gravy.",
      price: "$ 14.99",
    },
    {
      // id: 12,
      image: "https://img.freepik.com/premium-photo/chicken-biryani-plate-isolated-white-background-delicious-spicy-biryani-isolated_667286-5782.jpg",
      name: "Chicken Biryani",
      category: "Main Course",
      description: "Fragrant rice cooked with marinated chicken and spices.",
      price: "$ 16.99",
    },
    {
      // id: 13,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj0mZLoJJkeIarK9pJn4_lfh_5fplU3i9U_Q&s",
      name: "Pasta Alfredo",
      category: "Main Course",
      description: "Creamy white sauce pasta with mushrooms and parmesan.",
      price: "$ 12.99",
    },
    {
      // id: 14,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU8L6Oq5UgkQxcaze-zqfDJSfM8Ne5cOGjdg&s",
      name: "Veg Thali",
      category: "Main Course",
      description: "A wholesome platter with dal, sabzi, roti, and rice.",
      price: "$ 9.99",
    },

    // Beverages 
    {
      // id: 10,
      name: "Chicken Burger",
      category: "Beverages",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-5.png",
      description: "Juicy chicken patty served with lettuce, tomato, and cheese.",
      price: "$ 12.99",
    },{
      // id: 11,
      name: "Chicken Fajitas",
      category: "Beverages",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-6.png",
      description: "Sizzling chicken and vegetables served with warm flour tortillas.",
      price: "$ 16.99",
    },
    {
      // id:12,
      name: "Chicken Quesadilla",
      category: "Beverages",
      image: "https://bootstrapmade.com/content/demo/Yummy/assets/img/menu/menu-item-1.png",
      description: "Crispy chicken and cheese wrapped in a warm flour tortilla.",
      price: "$ 14.99",
    },
    {
      // id: 13,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpgBSyovcG7cXnFup0oTby9-5MBfTET3G1lw&s",
      name: "Mojito",
      category: "Beverage",
      description: "Refreshing lime and mint drink with soda.",
      price: "$ 5.99",
    },
    {
      // id: 14,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5u5iopS_aDDFBFrjn3i_-V6Ny2g_VtaXrnA&s",
      name: "Cold Coffee",
      category: "Beverage",
      description: "Chilled coffee blended with ice cream.",
      price: "$ 4.99",
    },
    {
      // id: 15,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF-uVQHx0xnyhjJv3YKgu6RId9diJ43o9ubQ&s",
      name: "Fruit Punch",
      category: "Beverage",
      description: "A mix of fresh fruit juices and soda.",
      price: "$ 6.99",
    },
    {
      // id: 16,
      image: "https://thumbs.dreamstime.com/b/traditional-tea-presentation-richly-colored-masala-chai-served-clay-cup-elegantly-displayed-white-background-aromatic-351553011.jpg",
      name: "Masala Chai",
      category: "Beverage",
      description: "Traditional Indian spiced tea.",
      price: "$ 4.99",
    },
    {
      // id: 17,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBVulwYVwVwIOuo2Jef74U5gN2gQsbQ9kfHA&s",
      name: "Lassi",
      category: "Beverage",
      description: "Thick and creamy yogurt-based drink (sweet or salty).",
      price: "$ 5.99",
    }
  ];