const Menu = [
    {
      id: 1,
      image: "src/assets/maggi.jpg",
      name: "Maggi",
      category: "breakfast",
      price: "12₹",
      description: "I love Maggi! It’s quick and tasty.",
    },
    {
      id: 2,
      image: "src/assets/allupakoida.jpg",
      name: "Allu Pakoida",
      category: "evening",
      price: "20₹",
      description: "A perfect evening snack to enjoy with tea.",
    },
{
    id: 3,
      image: "src/assets/chola.jpg",
      name: "Chola",
      category: "lunch",
      price: "25₹",
      description: "A delicious lunch option.",
    },
    {
      id: 4,
      image: "src/assets/momo.jpg",
      name: "Momo",
      category: "lunch",
      price: "25₹",
      description: "Another delicious lunch option.",
    },
    {
      id: 5,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2YPFXeqS9D_Qko6vuKa4LWT5WBX8VtX3vEA&s",
      name: "Veg Manchurian",
      category: "lunch",
      price: "20₹",
      description: "A healthy lunch option.",
    },
    {
        id: 6,
        image: "src/assets/paubhaji.jpg",
        name: "Pav Bhaji",
        category: "evening",
        price: "30₹",
        description: "A delicious blend of vegetables served with buttered pav.",
      },
      {
        id: 7,
        image: "src/assets/pizza.jpg",
        name: "Pizza",
        category: "dinner",
        price: "50₹",
        description: "Cheesy and loaded with toppings, perfect for dinner.",
      },
      {
        id: 8,
        image: "src/assets/puri.jpg",
        name: "Puri",
        category: "breakfast",
        price: "15₹",
        description: "A traditional Indian breakfast served with curry.",
      },
      {
        id: 9,
        image: "src/assets/rajmarice.jpg",
        name: "Rajma Rice",
        category: "lunch",
        price: "35₹",
        description: "A comforting combination of kidney beans and rice.",
      },
      {
        id: 10,
        image: "src/assets/rotiwithmeat.jpg",
        name: "Roti with Meat",
        category: "dinner",
        price: "40₹",
        description: "Soft rotis served with a delicious meat curry.",
      },
      {
        id: 11,
        image: "src/assets/sweet.jpg",
        name: "Sweet",
        category: "dessert",
        price: "10₹",
        description: "A perfect way to end your meal on a sweet note.",
      },
      {
        id: 12,
        image: "src/assets/vegthali.jpg",
        name: "Veg Thali",
        category: "lunch",
        price: "50₹",
        description: "A wholesome meal with multiple dishes served on a plate.",
      },
      {
        id: 13,
        image: "src/assets/samosa.jpg",
        name: "Samosa",
        category: "evening",
        price: "10₹",
        description: "Crispy and spicy, perfect for a quick snack.",
      },
      {
        id: 14,
        image: "src/assets/corn.jpg",
        name: "Corn",
        category: "snack",
        price: "15₹",
        description: "Freshly roasted corn, a healthy snack option.",
      }
      
  ];
  
  export default Menu;
  